version: "3.9"
services:
  service1:
    build:
      context: ./service1
      target: debugger1
    command: case.py
    ports:
      - 5678:5678
    volumes:
      - ./service1/sources:/workspace/sources
  service2:
    build:
      context: ./service2
      target: debugger2
    command: case.py
    ports:
      - 5000:5000
      - 5679:5678
    volumes:
      - ./service2/sources:/workspace/sources